CREATE OR REPLACE PUBLIC SYNONYM bind FOR bind
/
CREATE OR REPLACE PUBLIC SYNONYM json FOR t_json_value
/
CREATE OR REPLACE PUBLIC SYNONYM json_store FOR json_store
/
CREATE OR REPLACE PUBLIC SYNONYM json_table FOR json_table
/
CREATE OR REPLACE PUBLIC SYNONYM json_table_5 FOR json_table_5
/
CREATE OR REPLACE PUBLIC SYNONYM json_table_10 FOR json_table_10
/
CREATE OR REPLACE PUBLIC SYNONYM json_table_15 FOR json_table_15
/
CREATE OR REPLACE PUBLIC SYNONYM json_table_20 FOR json_table_20
/
